import { readFileSync, readdirSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const buttonsCss = readFileSync('src/styles/buttons-forms.css', 'utf8')
const homeCss = readFileSync('src/styles/home.css', 'utf8')
const navCss = readFileSync('src/styles/nav.css', 'utf8')
const aiDrawerCss = readFileSync('src/styles/ai-drawer.css', 'utf8')
const sidebarSource = readFileSync('src/components/AppSidebar.tsx', 'utf8')
const aiSource = readFileSync('src/components/AIAssistantPanel.tsx', 'utf8')
const appSource = readFileSync('src/App.tsx', 'utf8')
const importAssistantSource = readFileSync('src/components/ImportAssistantModal.tsx', 'utf8')
const dailyLogSource = readFileSync('src/components/DailyLogView.tsx', 'utf8')
const homeViewSource = readFileSync('src/components/HomeView.tsx', 'utf8')
const settingsViewSource = readFileSync('src/components/SettingsView.tsx', 'utf8')
const libraryViewSource = readFileSync('src/components/LibraryView.tsx', 'utf8')
const libraryCss = readFileSync('src/styles/library.css', 'utf8')
const workspaceCss = readFileSync('src/styles/workspace.css', 'utf8')
const stylesCssBundle = readdirSync('src/styles')
  .filter((file) => file.endsWith('.css'))
  .map((file) => readFileSync(`src/styles/${file}`, 'utf8'))
  .join('\n')

describe('global design alignment contract', () => {
  it('aliases legacy button classes to the design-pack btn system', () => {
    expect(buttonsCss).toContain('.btn,')
    expect(buttonsCss).toContain('.primary-button,')
    expect(buttonsCss).toContain('.ghost-button')
    expect(buttonsCss).toContain('.btn.primary,')
    expect(buttonsCss).toContain('.btn.ghost,')
    expect(buttonsCss).toContain('.btn.subtle')
    expect(buttonsCss).toContain('.btn.icon-only')
  })

  it('keeps the app sidebar compact mode icon-only and design-token sized', () => {
    expect(homeCss).toContain('--sidebar-collapsed-width')
    expect(homeCss).toContain('.home-sidebar.is-collapsed .home-nav-label')
    expect(homeCss).toContain('.home-sidebar.is-collapsed .home-nav-aside')
    expect(navCss).toContain('--section-nav-collapsed-width')
    expect(navCss).toContain('width: var(--section-nav-collapsed-width)')
    expect(sidebarSource).toContain("className='btn ghost icon-only home-sidebar-collapse'")
    expect(sidebarSource).toContain("className='btn ghost sm full-width'")
  })

  it('aligns the AI drawer context controls with the design pack', () => {
    expect(aiSource).toContain('provider-row')
    expect(aiSource).toContain('tools-toggle')
    expect(aiSource).toContain('article-row')
    expect(aiSource).toContain('scope-row')
    expect(aiSource).toContain('tools-toggle-dot')
    expect(aiDrawerCss).toContain('.provider-row')
    expect(aiDrawerCss).toContain('.tools-toggle')
    expect(aiDrawerCss).toContain('.article-row')
    expect(aiDrawerCss).toContain('.scope-row')
    expect(aiDrawerCss).toContain('.seg-btn')
  })

  it('reserves drawer space without creating page-level horizontal scroll', () => {
    expect(aiDrawerCss).toContain('body.ai-drawer-open {')
    expect(aiDrawerCss).toMatch(/body\.ai-drawer-open\s*{[^}]*overflow-x: hidden/s)
    expect(aiDrawerCss).toContain('width: calc(100vw - var(--ai-drawer-width')
    expect(aiDrawerCss).toContain('max-width: calc(100vw - var(--ai-drawer-width')
    expect(aiDrawerCss).toContain('body.ai-drawer-open .workspace-top')
    expect(aiDrawerCss).toContain('grid-template-columns: minmax(0, 1fr)')
    expect(aiDrawerCss).toContain('body.ai-drawer-open .workspace-grid.is-rail-open')
    expect(aiDrawerCss).toContain('body.ai-drawer-open .article-right-rail')
  })

  it('persists AI drawer resize only at the end of a drag', () => {
    expect(aiSource).toContain('persistWidth')
    expect(aiSource).toContain('persistWidth(widthRef.current)')
    expect(aiSource).not.toContain(`useEffect(() => {
    if (typeof window === 'undefined') return
    try { window.localStorage.setItem(WIDTH_KEY, String(width)) }`)
  })

  it('keeps import/export labels direct without visible explanatory helper text', () => {
    expect(appSource).toContain('分享 MD')
    expect(appSource).toContain('回导 MD')
    expect(appSource).not.toContain('普通 MD')
    expect(appSource).not.toContain('export-help')
    expect(appSource).not.toContain('阅读版用于分享')
    expect(appSource).not.toContain('不保证')
    expect(appSource).not.toContain('导出前 LLM 自动')
    expect(appSource).not.toContain('成本更高')
    expect(appSource).not.toContain('LaTeX 工程')
    expect(appSource).toContain("'DOCX…'")
    expect(appSource).toContain("'DOCX'")
    expect(importAssistantSource).toContain('每章一块')
    expect(importAssistantSource).toContain('小标题分块')
    expect(importAssistantSource).toContain('整篇一块')
    expect(importAssistantSource).toContain('拆分')
    expect(importAssistantSource).not.toContain('确认后才写入')
    expect(importAssistantSource).not.toContain('可以切换')
    expect(importAssistantSource).not.toContain('请保留')
    expect(importAssistantSource).not.toContain('导入助手需要')
    expect(importAssistantSource).not.toContain('AI Import Assistant')
    expect(importAssistantSource).not.toContain('Preview</p>')
    expect(importAssistantSource).not.toContain('className="eyebrow">导入')
    expect(importAssistantSource).not.toContain('className="eyebrow">预览')
    expect(importAssistantSource).toContain('粘贴文本')
    expect(importAssistantSource).not.toContain('或直接粘贴文本')
    expect(importAssistantSource).toContain('modal-body import-assistant-body')
    expect(importAssistantSource).toContain('import-preview-actions')
  })

  it('keeps daily, AI, and article toolbar copy direct and design-aligned', () => {
    expect(appSource).toContain('导入正文/审稿')
    expect(appSource).not.toContain('导入正文/审稿文本')
    expect(appSource).toContain('套斜体规范')
    expect(dailyLogSource).toContain('今天还没有进展记录。')
    expect(dailyLogSource).toContain('写下今天计划。')
    expect(dailyLogSource).toContain('记录一项进展…')
    expect(dailyLogSource).not.toContain('随便写')
    expect(dailyLogSource).not.toContain('空白强')
    expect(dailyLogSource).not.toContain('大概干了啥')
    expect(dailyLogSource).not.toContain('接着搞什么')
    expect(dailyLogSource).not.toContain('写一笔')
    expect(homeViewSource).not.toContain('先随便记一段')
    expect(homeViewSource).not.toContain('正安静')
    expect(homeViewSource).not.toContain('适合深写')
    expect(homeViewSource).toContain("if (hour < 18) return { greeting: '下午好', mood: '正沉潜', period: 'afternoon' }")
    expect(homeViewSource).toContain('your study is <em>{tod.mood}</em>.')
    expect(aiSource).toContain('跟 AI 说你想做什么')
    expect(aiSource).not.toContain('从当前稿件继续')
    expect(aiSource).not.toContain('输入任务。Enter')
    expect(workspaceCss).toMatch(/\.export-group\s*{[^}]*margin-left: auto/s)
    expect(workspaceCss).toMatch(/\.export-buttons \.btn\s*{[^}]*border-color: transparent/s)
    expect(workspaceCss).toContain('grid-template-columns: minmax(0, 1fr)')
    expect(workspaceCss).toContain('.workspace-top > *')
    expect(workspaceCss).toContain('overflow-wrap: anywhere')
    expect(stylesCssBundle).not.toMatch(/letter-spacing:\s*-/)
  })

  it('keeps screenshot-facing settings and library controls polished', () => {
    expect(settingsViewSource).not.toContain('☺')
    expect(settingsViewSource).not.toContain('𝒁')
    expect(settingsViewSource).not.toContain('𝑨')
    expect(libraryCss).toContain('.library-card-delete')
    expect(libraryCss).toContain('opacity: 0')
    expect(libraryCss).toContain('.library-card:hover .library-card-delete')
    expect(libraryViewSource).not.toContain('fontSize: 16')
  })
})
